[package]
name = "aoc25"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
